network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
    eth1:
      addresses:
        - 10.121.84.1/28
    eth2:
      addresses:
        - 10.121.85.1/28
    eth3:
      addresses:
        - 10.121.86.1/28
